// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: order.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderExperimentService_GetOrderDepthZero_FullMethodName = "/orderexperiment.OrderExperimentService/GetOrderDepthZero"
	OrderExperimentService_GetOrderDepthTwo_FullMethodName  = "/orderexperiment.OrderExperimentService/GetOrderDepthTwo"
	OrderExperimentService_GetOrderDepthFour_FullMethodName = "/orderexperiment.OrderExperimentService/GetOrderDepthFour"
	OrderExperimentService_GetOrderOne_FullMethodName       = "/orderexperiment.OrderExperimentService/GetOrderOne"
	OrderExperimentService_GetOrderHundred_FullMethodName   = "/orderexperiment.OrderExperimentService/GetOrderHundred"
	OrderExperimentService_GetOrderThousand_FullMethodName  = "/orderexperiment.OrderExperimentService/GetOrderThousand"
)

// OrderExperimentServiceClient is the client API for OrderExperimentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderExperimentService exposes GET-only unary RPCs for the
// depth-scenario and element-count-scenario investigation.
// GetOrderDepthZero, GetOrderOne, GetOrderHundred, and
// GetOrderThousand all share the same flat (depth-0) shape and
// differ only in seeded array length; GetOrderDepthTwo and
// GetOrderDepthFour use progressively deeper single-object chains
// at a fixed array length of 1.
type OrderExperimentServiceClient interface {
	GetOrderDepthZero(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error)
	GetOrderDepthTwo(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthTwoResponse, error)
	GetOrderDepthFour(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthFourResponse, error)
	GetOrderOne(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error)
	GetOrderHundred(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error)
	GetOrderThousand(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error)
}

type orderExperimentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderExperimentServiceClient(cc grpc.ClientConnInterface) OrderExperimentServiceClient {
	return &orderExperimentServiceClient{cc}
}

func (c *orderExperimentServiceClient) GetOrderDepthZero(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthZeroResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderDepthZero_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExperimentServiceClient) GetOrderDepthTwo(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthTwoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthTwoResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderDepthTwo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExperimentServiceClient) GetOrderDepthFour(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthFourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthFourResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderDepthFour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExperimentServiceClient) GetOrderOne(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthZeroResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExperimentServiceClient) GetOrderHundred(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthZeroResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderHundred_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderExperimentServiceClient) GetOrderThousand(ctx context.Context, in *OrderEmpty, opts ...grpc.CallOption) (*OrderDepthZeroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDepthZeroResponse)
	err := c.cc.Invoke(ctx, OrderExperimentService_GetOrderThousand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderExperimentServiceServer is the server API for OrderExperimentService service.
// All implementations must embed UnimplementedOrderExperimentServiceServer
// for forward compatibility.
//
// OrderExperimentService exposes GET-only unary RPCs for the
// depth-scenario and element-count-scenario investigation.
// GetOrderDepthZero, GetOrderOne, GetOrderHundred, and
// GetOrderThousand all share the same flat (depth-0) shape and
// differ only in seeded array length; GetOrderDepthTwo and
// GetOrderDepthFour use progressively deeper single-object chains
// at a fixed array length of 1.
type OrderExperimentServiceServer interface {
	GetOrderDepthZero(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error)
	GetOrderDepthTwo(context.Context, *OrderEmpty) (*OrderDepthTwoResponse, error)
	GetOrderDepthFour(context.Context, *OrderEmpty) (*OrderDepthFourResponse, error)
	GetOrderOne(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error)
	GetOrderHundred(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error)
	GetOrderThousand(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error)
	mustEmbedUnimplementedOrderExperimentServiceServer()
}

// UnimplementedOrderExperimentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderExperimentServiceServer struct{}

func (UnimplementedOrderExperimentServiceServer) GetOrderDepthZero(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDepthZero not implemented")
}
func (UnimplementedOrderExperimentServiceServer) GetOrderDepthTwo(context.Context, *OrderEmpty) (*OrderDepthTwoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDepthTwo not implemented")
}
func (UnimplementedOrderExperimentServiceServer) GetOrderDepthFour(context.Context, *OrderEmpty) (*OrderDepthFourResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDepthFour not implemented")
}
func (UnimplementedOrderExperimentServiceServer) GetOrderOne(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderOne not implemented")
}
func (UnimplementedOrderExperimentServiceServer) GetOrderHundred(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderHundred not implemented")
}
func (UnimplementedOrderExperimentServiceServer) GetOrderThousand(context.Context, *OrderEmpty) (*OrderDepthZeroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderThousand not implemented")
}
func (UnimplementedOrderExperimentServiceServer) mustEmbedUnimplementedOrderExperimentServiceServer() {
}
func (UnimplementedOrderExperimentServiceServer) testEmbeddedByValue() {}

// UnsafeOrderExperimentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderExperimentServiceServer will
// result in compilation errors.
type UnsafeOrderExperimentServiceServer interface {
	mustEmbedUnimplementedOrderExperimentServiceServer()
}

func RegisterOrderExperimentServiceServer(s grpc.ServiceRegistrar, srv OrderExperimentServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderExperimentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderExperimentService_ServiceDesc, srv)
}

func _OrderExperimentService_GetOrderDepthZero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderDepthZero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderDepthZero_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderDepthZero(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExperimentService_GetOrderDepthTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderDepthTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderDepthTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderDepthTwo(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExperimentService_GetOrderDepthFour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderDepthFour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderDepthFour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderDepthFour(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExperimentService_GetOrderOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderOne(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExperimentService_GetOrderHundred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderHundred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderHundred_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderHundred(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderExperimentService_GetOrderThousand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderExperimentServiceServer).GetOrderThousand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderExperimentService_GetOrderThousand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderExperimentServiceServer).GetOrderThousand(ctx, req.(*OrderEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderExperimentService_ServiceDesc is the grpc.ServiceDesc for OrderExperimentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderExperimentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderexperiment.OrderExperimentService",
	HandlerType: (*OrderExperimentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderDepthZero",
			Handler:    _OrderExperimentService_GetOrderDepthZero_Handler,
		},
		{
			MethodName: "GetOrderDepthTwo",
			Handler:    _OrderExperimentService_GetOrderDepthTwo_Handler,
		},
		{
			MethodName: "GetOrderDepthFour",
			Handler:    _OrderExperimentService_GetOrderDepthFour_Handler,
		},
		{
			MethodName: "GetOrderOne",
			Handler:    _OrderExperimentService_GetOrderOne_Handler,
		},
		{
			MethodName: "GetOrderHundred",
			Handler:    _OrderExperimentService_GetOrderHundred_Handler,
		},
		{
			MethodName: "GetOrderThousand",
			Handler:    _OrderExperimentService_GetOrderThousand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
