// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/student.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is used for RPCs that take no parameters.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{0}
}

// Course represents a single course entry within a semester.
type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{1}
}

func (x *Course) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *Course) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// SemesterRecord represents one semester's academic record.
type SemesterRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semester      int32                  `protobuf:"varint,1,opt,name=semester,proto3" json:"semester,omitempty"`
	SemesterGpa   float32                `protobuf:"fixed32,2,opt,name=semester_gpa,json=semesterGpa,proto3" json:"semester_gpa,omitempty"`
	Courses       []*Course              `protobuf:"bytes,3,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemesterRecord) Reset() {
	*x = SemesterRecord{}
	mi := &file_proto_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemesterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemesterRecord) ProtoMessage() {}

func (x *SemesterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemesterRecord.ProtoReflect.Descriptor instead.
func (*SemesterRecord) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{2}
}

func (x *SemesterRecord) GetSemester() int32 {
	if x != nil {
		return x.Semester
	}
	return 0
}

func (x *SemesterRecord) GetSemesterGpa() float32 {
	if x != nil {
		return x.SemesterGpa
	}
	return 0
}

func (x *SemesterRecord) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// AcademicData represents a student's academic program information.
type AcademicData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Faculty         string                 `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	StudyProgram    string                 `protobuf:"bytes,2,opt,name=study_program,json=studyProgram,proto3" json:"study_program,omitempty"`
	CurrentSemester int32                  `protobuf:"varint,3,opt,name=current_semester,json=currentSemester,proto3" json:"current_semester,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcademicData) Reset() {
	*x = AcademicData{}
	mi := &file_proto_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcademicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcademicData) ProtoMessage() {}

func (x *AcademicData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcademicData.ProtoReflect.Descriptor instead.
func (*AcademicData) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{3}
}

func (x *AcademicData) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *AcademicData) GetStudyProgram() string {
	if x != nil {
		return x.StudyProgram
	}
	return ""
}

func (x *AcademicData) GetCurrentSemester() int32 {
	if x != nil {
		return x.CurrentSemester
	}
	return 0
}

// Student represents a single student record.
type Student struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender          string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	AcademicData    *AcademicData          `protobuf:"bytes,4,opt,name=academic_data,json=academicData,proto3" json:"academic_data,omitempty"`
	AcademicHistory []*SemesterRecord      `protobuf:"bytes,5,rep,name=academic_history,json=academicHistory,proto3" json:"academic_history,omitempty"`
	CumulativeGpa   float32                `protobuf:"fixed32,6,opt,name=cumulative_gpa,json=cumulativeGpa,proto3" json:"cumulative_gpa,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_proto_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{4}
}

func (x *Student) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Student) GetAcademicData() *AcademicData {
	if x != nil {
		return x.AcademicData
	}
	return nil
}

func (x *Student) GetAcademicHistory() []*SemesterRecord {
	if x != nil {
		return x.AcademicHistory
	}
	return nil
}

func (x *Student) GetCumulativeGpa() float32 {
	if x != nil {
		return x.CumulativeGpa
	}
	return 0
}

// StudentResponse always wraps student records in a list.
// - Applies uniformly to all three read sizes (small=1, medium=100, large=1000).
// - Keeps the response shape identical across sizes, so only entry count varies.
type StudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Student             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_proto_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{5}
}

func (x *StudentResponse) GetData() []*Student {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreateStudentResponse acknowledges a successful write.
// - Deliberately minimal, POST measures deserialization cost of the request, not the size of the response.
type CreateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentResponse) Reset() {
	*x = CreateStudentResponse{}
	mi := &file_proto_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentResponse) ProtoMessage() {}

func (x *CreateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{6}
}

func (x *CreateStudentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_student_proto protoreflect.FileDescriptor

const file_proto_student_proto_rawDesc = "" +
	"\n" +
	"\x13proto/student.proto\x12\astudent\"\a\n" +
	"\x05Empty\"`\n" +
	"\x06Course\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\"z\n" +
	"\x0eSemesterRecord\x12\x1a\n" +
	"\bsemester\x18\x01 \x01(\x05R\bsemester\x12!\n" +
	"\fsemester_gpa\x18\x02 \x01(\x02R\vsemesterGpa\x12)\n" +
	"\acourses\x18\x03 \x03(\v2\x0f.student.CourseR\acourses\"x\n" +
	"\fAcademicData\x12\x18\n" +
	"\afaculty\x18\x01 \x01(\tR\afaculty\x12#\n" +
	"\rstudy_program\x18\x02 \x01(\tR\fstudyProgram\x12)\n" +
	"\x10current_semester\x18\x03 \x01(\x05R\x0fcurrentSemester\"\xfb\x01\n" +
	"\aStudent\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12:\n" +
	"\racademic_data\x18\x04 \x01(\v2\x15.student.AcademicDataR\facademicData\x12B\n" +
	"\x10academic_history\x18\x05 \x03(\v2\x17.student.SemesterRecordR\x0facademicHistory\x12%\n" +
	"\x0ecumulative_gpa\x18\x06 \x01(\x02R\rcumulativeGpa\"7\n" +
	"\x0fStudentResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.student.StudentR\x04data\"1\n" +
	"\x15CreateStudentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8e\x02\n" +
	"\x0eStudentService\x12<\n" +
	"\x10GetStudentsSmall\x12\x0e.student.Empty\x1a\x18.student.StudentResponse\x12=\n" +
	"\x11GetStudentsMedium\x12\x0e.student.Empty\x1a\x18.student.StudentResponse\x12<\n" +
	"\x10GetStudentsLarge\x12\x0e.student.Empty\x1a\x18.student.StudentResponse\x12A\n" +
	"\rCreateStudent\x12\x10.student.Student\x1a\x1e.student.CreateStudentResponseB-Z+scaling-up-rest-vs-grpc/internal/data/modelb\x06proto3"

var (
	file_proto_student_proto_rawDescOnce sync.Once
	file_proto_student_proto_rawDescData []byte
)

func file_proto_student_proto_rawDescGZIP() []byte {
	file_proto_student_proto_rawDescOnce.Do(func() {
		file_proto_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)))
	})
	return file_proto_student_proto_rawDescData
}

var file_proto_student_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_student_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: student.Empty
	(*Course)(nil),                // 1: student.Course
	(*SemesterRecord)(nil),        // 2: student.SemesterRecord
	(*AcademicData)(nil),          // 3: student.AcademicData
	(*Student)(nil),               // 4: student.Student
	(*StudentResponse)(nil),       // 5: student.StudentResponse
	(*CreateStudentResponse)(nil), // 6: student.CreateStudentResponse
}
var file_proto_student_proto_depIdxs = []int32{
	1, // 0: student.SemesterRecord.courses:type_name -> student.Course
	3, // 1: student.Student.academic_data:type_name -> student.AcademicData
	2, // 2: student.Student.academic_history:type_name -> student.SemesterRecord
	4, // 3: student.StudentResponse.data:type_name -> student.Student
	0, // 4: student.StudentService.GetStudentsSmall:input_type -> student.Empty
	0, // 5: student.StudentService.GetStudentsMedium:input_type -> student.Empty
	0, // 6: student.StudentService.GetStudentsLarge:input_type -> student.Empty
	4, // 7: student.StudentService.CreateStudent:input_type -> student.Student
	5, // 8: student.StudentService.GetStudentsSmall:output_type -> student.StudentResponse
	5, // 9: student.StudentService.GetStudentsMedium:output_type -> student.StudentResponse
	5, // 10: student.StudentService.GetStudentsLarge:output_type -> student.StudentResponse
	6, // 11: student.StudentService.CreateStudent:output_type -> student.CreateStudentResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_student_proto_init() }
func file_proto_student_proto_init() {
	if File_proto_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_student_proto_goTypes,
		DependencyIndexes: file_proto_student_proto_depIdxs,
		MessageInfos:      file_proto_student_proto_msgTypes,
	}.Build()
	File_proto_student_proto = out.File
	file_proto_student_proto_goTypes = nil
	file_proto_student_proto_depIdxs = nil
}
